# cnav:
#   class: UDP
#   port: 57001
#   filebase: /home/mcarloni_admin/my_git/shipop_works/truewind/openrvdas/rawdata/at20250730_1500_stripped.GPS

# gyro:
#   class: UDP
#   port: 57002
#   filebase: /home/mcarloni_admin/my_git/shipop_works/truewind/openrvdas/rawdata/at20250730_1500_stripped.HDT

rs485:
  class: UDP
  port: 57204
  filebase: /home/sssg/openrvdas_support/logs/ar20250218_1000_sorted.rs485_all